const allEvents = [
  {
    id: "food_adulteration_and_smart_consumer",
    name: "Food Adulteration & Smart Consumer",
    club_name: "Citizen Consumer Club",
    description: "Awareness about the consumer rights",
    total_seats: 200,
    venue: "Electrical Seminar Hall",
    date: "23 September, 2022",
    start_time: "11:30:00",
    end_time: "13:00:00",
    prize: 0,
    organizer: "Chethan Kumar C",
    phone: "+919659379741",
    isOpen: 0,
    formLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=CM6lTXfigEWzOHzxtefjukE8TYIBdMdJmM9Ms5HN5dNURFhBUU9MMUkzSVM1QTgxMk1STU9JVjQwQS4u",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/ccc_doc.pdf?alt=media&token=3ecf920f-843d-4f74-910a-72357d0b0e46",
  },
  {
    id: "indian_heritage_quiz",
    name: "Indian Heritage Quiz",
    club_name: "Gyan - Quiz Planet",
    description: "This is gonna be a quiz based event with an initial preliminary round and other 3 rounds. Finally 3 teams will be selected and awarded. Only team participants are allowed, irrespective of year and department.",
    total_seats: 50,
    venue: "Mechanical Seminar Hall",
    date: "24 September, 2022",
    start_time: "09:30:00",
    end_time: "11:00:00",
    prize: 6000,
    organizer: "Susmitha VG",
    phone: "+918012459999",
    isOpen: 0,
    formLink: "https://docs.google.com/forms/d/16-04lw8gNwiggo6gz2ZVWFG5a1xCTFL9_sf4dmBj6nA/viewform?edit_requested=true",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/evn_doc.png?alt=media&token=c2267eb3-27e9-4869-b6a0-1b7be88abd8b",
  },
  {
    id: "bosses_in_the_treasure",
    name: "Bosses In The Treasure",
    club_name: "Student Guild of Service",
    description: "A total of 20 teams each consisting of 5 members. First team to find all the clues will be awarded first place and second and third accordingly.",
    total_seats: 100,
    venue: "SGS Cabin",
    date: "23 September, 2022",
    start_time: "11:30:00",
    end_time: "13:00:00",
    prize: 6000,
    organizer: "Subhiksha K",
    phone: "+91 6381269727",
    isOpen: 0,
    formLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=CM6lTXfigEWzOHzxtefjurzolvA_2zRIox93zMH7TGVUOERSRE5DNDlHTEMwT1lHRVZDTjJEMk1TNC4u",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/treasurehunt_doc.pdf?alt=media&token=1c26c857-bb98-430c-bab5-d03e819ea51c",
  },
  {
    id: "drawing_competition",
    name: "Drawing Competition",
    club_name: "FAC Doodlers",
    description: "First round will be conducted through Google forms in the topic social responsibility and shortlisted by our alumni's. Second round will conducted for shortlisted students in topic Environmental responsibility.",
    total_seats: 100,
    venue: "A-428",
    date: "24 September, 2022",
    start_time: "11:20:00",
    end_time: "12:45:00",
    prize: 6000,
    organizer: "Dharun T",
    phone: "+91 7604904165",
    isOpen: 0,
    formLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=CM6lTXfigEWzOHzxtefjugfzSmMoahhBmuIGPiboaDJUNzNONjNIQTNINFBITTYwQVBEVkFEMjNVNy4u",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/doodlers_doc.pdf?alt=media&token=559e3933-1738-4522-aaaf-cb4918905ec0",
  },
  {
    id: "insight_on_social_and_political_responsibilities",
    name: "Insight On Social & Political Responsibilities",
    club_name: "Youth Parliament & Rostrum Club",
    description: "Round 1 :-Shipwreck event.Student should speak their wayout incase of drowning in a ship as the character given to them.10-15 students will be selected from first round by the Alumni of Yp. Round 2 Newspaper Narration Student should gain some insight from a list of newspaper article given to them. They should give a speech on the topic chosen by them from the list. 3 students will be selected as winners by the Alumni.",
    total_seats: 70,
    venue: "Electrical Seminar Hall",
    date: "24 September, 2022",
    start_time: "9:30:00",
    end_time: "11:00:00",
    prize: 0,
    organizer: "Vijay R",
    phone: "+918056384423",
    isOpen: 0,
    formLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__UBSdqJUMUdGQllJUkw0REI4UDdDUlNKMVVESk5URC4u",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/muthamil_doc.pdf?alt=media&token=feb0501c-56e5-46fd-82a3-62d36e722a46",
  },
  {
    id: "konneckt_the_connect",
    name: "Konneckt the Connect",
    club_name: "Student Guild of Service",
    description: "A total of 25 teams each consisting of 2 members. The event will moreover be like the Television show called Connexion. The participants have to find the correct connect word/answer by connecting the given clues.",
    total_seats: 50,
    venue: "Electrical Seminar Hall",
    date: "24 September, 2022",
    start_time: "11:20:00",
    end_time: "12:45:00",
    prize: 6000,
    organizer: "Thinhesh A C",
    phone: "8825581324",
    isOpen: 0,
    formLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=CM6lTXfigEWzOHzxtefjurzolvA_2zRIox93zMH7TGVUMFU1TDJNU1BBR05KMzdUU1dBRVhWVUZPRy4u",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/connections_doc.pdf?alt=media&token=d510f343-dad6-4d90-8582-6cfbef35d35f",
  },
  {
    id: "paadhaivali_pattimandram",
    name: "பாதைவழிப் பட்டிமன்றம்",
    club_name: "Muthamil Mandram",
    description: "Single round debate on the given topic . Depending on the valid points the best speakers are choosen from both side.",
    total_seats: 100,
    venue: "CC Hall",
    date: "23 September, 2022",
    start_time: "10:00:00",
    end_time: "11:30:00",
    prize: 6000,
    organizer: "Preetha R",
    phone: "+919344417292",
    isOpen: 0,
    formLink: "https://docs.google.com/forms/d/e/1FAIpQLSfZFuGrt-CfwOGKlt5RZFKkQyKRPso6HHepgORJhE09PkLN3w/viewform",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/muthamil_doc.pdf?alt=media&token=c60d51a3-9bf7-4f9f-b091-cdd2dd7963af",
  },
  {
    id: "ethical_clips",
    name: "Ethical Clips",
    club_name: "Film Club",
    description: "Only one round is conducted.Few clips from various movies conveying basic ethics of life.The participants can view their performance through Menti meter which will be displayed on the screen and prices for the winners will be awarded.",
    total_seats: 80,
    venue: "Mechanical Seminar Hall",
    date: "23 September, 2022",
    start_time: "10:00:00",
    end_time: "11:30:00",
    prize: 3250,
    organizer: "Sree Vaishak S",
    phone: "+917708582912",
    isOpen: 0,
    formLink: "https://forms.office.com/Pages/ResponsePage.aspx?id=CM6lTXfigEWzOHzxtefjurK01st-svpCh1eYDU_RFCdUREZFTUpEWFpCWk0wTUtEUTZMSUJOSEVVTC4u",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/film_doc.pdf?alt=media&token=25e16d2e-ada0-47d6-a809-8214df6d383f",
  },
  {
    id: "social_awareness_performance",
    name: "Social Awareness Performance",
    club_name: "Fine Arts Club",
    description: "This part will be a entertaining session, we gonna perform in front of 2000 people. Dance , music and mime skit will be perform on the stage.",
    total_seats: 0,
    venue: "Centenary Centre hall",
    date: "24 September, 2022",
    start_time: "15:15:00",
    end_time: "16:45:00",
    prize: 0,
    organizer: "Karthik K",
    phone: "+918825929245",
    isOpen: 0,
    formLink: "",
    doc: "",
  },
  {
    id: "disaster_management_training",
    name: "Disaster Management Training",
    club_name: "Youth Red Cross",
    description: "This part will be a entertaining session, we gonna perform in front of 2000 people. Dance , music and mime skit will be perform on the stage.",
    total_seats: 150,
    venue: "Mechanical Seminar Hall",
    date: "24 September, 2022",
    start_time: "12:00:00",
    end_time: "13:00:00",
    prize: 0,
    organizer: "Abdul Muqsid M",
    phone: "+919629057760",
    isOpen: 0,
    formLink: "",
    doc: "https://firebasestorage.googleapis.com/v0/b/tehnofete.appspot.com/o/yrc_doc.pdf?alt=media&token=d06545f2-67b1-4b18-b65d-30259d15dace",
  }
];

module.exports = allEvents;
